apiVersion: sparkoperator.hpe.com/v1beta2
kind: SparkApplication
metadata:
  name: site-poly-daily-load-secure
  namespace: data-engineering
spec:
  sparkConf:
    spark.hadoop.fs.dtap.impl: com.bluedata.hadoop.bdfs.Bdfs
    spark.hadoop.fs.AbstractFileSystem.dtap.impl: com.bluedata.hadoop.bdfs.BdAbstractFS
    spark.hadoop.fs.dtap.impl.disable.cache: 'false'
    spark.driver.extraClassPath: local:///opt/bdfs/bluedata-dtap.jar
    spark.executor.extraClassPath: local:///opt/bdfs/bluedata-dtap.jar
  type: Python
  sparkVersion: 2.4.7
  pythonVersion: '3'
  mode: cluster
  image: gcr.io/mapr-252711/spark-py-2.4.7:202104010902C
  imagePullPolicy: Always
  mainApplicationFile: dtap://dnb_dtap/dnb_code/site_poly_cu.py
  restartPolicy:
    type: Never
  imagePullSecrets:
  - imagepull
  driver:
    cores: 1
    coreLimit: 1000m
    memory: 512m
    labels:
      version: 2.4.7
      hpecp.hpe.com/dtap: hadoop2
  executor:
    cores: 1
    coreLimit: 1000m
    instances: 2
    memory: 512m
    labels:
      version: 2.4.7
      hpecp.hpe.com/dtap: hadoop2
