apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: mlops-dataiku
  labels:
     hpecp.hpe.com/dtap: hadoop2
     hpecp.hpe.com/fsmount: mlops-dataiku
spec:
  restartPolicy: Never
  shareProcessNamespace: true
  containers:
  - name: app
    image: devuser2021/sample-docker:latest
    command: ["python3"]
    args: ["/bd-fs-mnt/TenantShare/repo/test/test1.py"]
    imagePullPolicy: Never
    resources:
      limits:
        cpu: "500m"
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "4Gi"
