apiVersion: v1
kind: Pod
metadata:
  name: k8spod-
  namespace: test
  labels:
     hpecp.hpe.com/dtap: hadoop2
     hpecp.hpe.com/fsmount: test
spec:
  restartPolicy: Never
  shareProcessNamespace: true
  containers:
  - name: app
    image: devuser2021/sample-docker:latest
    command: ["python3"]
    args: ["/bd-fs-mnt/project_repo/code/test.py"]
    imagePullPolicy: Never
    resources:
      limits:
        cpu: "500m"
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "4Gi"
